# Generated by Django 5.0.3 on 2024-11-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tool_alter_scan_tool_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='tool_used',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
